on:
  push:
    branches: main

env:
  VITE_APIKEY: ${{ secrets.VITE_APIKEY }}
  VITE_AUTHDOMAIN: ${{ secrets.VITE_AUTHDOMAIN }}
  VITE_PROJECTID: ${{ secrets.VITE_PROJECTID }}
  VITE_STORAGEBUCKET: ${{ secrets.VITE_STORAGEBUCKET }}
  VITE_MESSAGINGSENDERID: ${{ secrets.VITE_MESSAGINGSENDERID }}
  VITE_APPID: ${{ secrets.VITE_APPID }}

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      # Step to test DNS resolution
      - name: Test DNS resolution
        run: |
          nslookup ${{ secrets.ftp_server }}

      # Use SFTP Deploy Action (Option 1)
      - name: SFTP Deploy
        uses: easeic/sftp-deploy@v1.0.0
        with:
          username: ${{ secrets.ftp_name }}
          password: ${{ secrets.ftp_password }}
          host: ${{ secrets.ftp_server }}  # Your server's domain or IP address
          port: 22  # Default SFTP port, change if necessary
          local_path: ./dist
          remote_path: /path/on/server  # Replace with your server's path
