on:
  push:
    branches: main

env:
  VITE_APIKEY: ${{ secrets.VITE_APIKEY }}
  VITE_AUTHDOMAIN: ${{ secrets.VITE_AUTHDOMAIN }}
  VITE_PROJECTID: ${{ secrets.VITE_PROJECTID }}
  VITE_STORAGEBUCKET: ${{ secrets.VITE_STORAGEBUCKET }}
  VITE_MESSAGINGSENDERID: ${{ secrets.VITE_MESSAGINGSENDERID }}
  VITE_APPID: ${{ secrets.VITE_APPID }}

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      # Step to test DNS resolution
      - name: Test DNS resolution
        run: |
          nslookup ${{ secrets.ftp_server }}

      # Add Retry logic and Timeout handling
      - name: Retry FTP Deploy
        uses: devmasx/timeout-action@v1
        with:
          timeout_seconds: 30
          interval_seconds: 10
          max_retries: 3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server }}  # You can replace this with IP address if DNS issue persists
          username: ${{ secrets.ftp_name }}
          password: ${{ secrets.ftp_password }}
          dangerous-clean-slate: true
          local-dir: ./dist/
          timeout: 60000  # Increase timeout to 60 seconds
